version: '3.4'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./SampleCollections:/usr/local/sampleCollections
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine
    volumes:
      - './:/home/node/app:rw,consistent'
    working_dir: '/home/node/app'
    environment:
      MONGODB_USER: "root"
      MONGODB_PASS: "password"
      MONGODB_DBNAME: "SampleCollections"
      JWT_SECRET: "MyBestSecret"
    command: 'npm start'
    depends_on:
      - mongo
    ports:
      - 127.0.0.1:3000:3000
